name: DHBW-NLP-CrowdFlow
channels:
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - pandas
  - python==3.11.10
  - pytorch
  - scikit-learn
  - transformers
  - nltk==3.8.1
  - numpy
  - scipy
  - seaborn
  - plotly
  - streamlit
