name: Test Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Jupyter Notebooks
      shell: bash
      run: |
        for notebook in $(find ./src -name "*.ipynb"); do
          echo "Running $notebook"
          jupyter execute $notebook
        done
