name: Test Jupyter Notebooks with Pip

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  test-run-notebooks-linux:
    name: Test Run Jupyter Notebooks on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Installation
      run: |
        python --version
        pip list

    - name: Run Jupyter Notebooks
      run: |
        for notebook in $(find ./src -name "*.ipynb"); do
          echo "Running $notebook"
          jupyter nbconvert --to notebook --execute "$notebook" --output "$(basename \"${notebook%.ipynb}_linux_executed.ipynb\")"
          echo ""
        done

    - name: Upload Executed Notebooks as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebooks-linux
        path: ./src/**/*_linux_executed.ipynb

  test-run-notebooks-windows:
    name: Test Run Jupyter Notebooks on Windows
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Installation
      run: |
        python --version
        pip list

    - name: Run Jupyter Notebooks
      run: |
        cmd /c "FOR /R ./src %G IN (*.ipynb) DO echo Running %G & jupyter nbconvert --to notebook --execute %G --output %~dpnG_windows_executed.ipynb & echo Finished %G"

    - name: List Files
      run: |
        dir
        dir src

    - name: Upload Executed Notebooks as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebooks-windows
        path: ./src/**/*_windows_executed.ipynb