name: Test Jupyter Notebooks with Python 3.11.9

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-run-notebooks-linux:
    name: Test Run Jupyter Notebooks on Ubuntu
    runs-on: ["self-hosted", "Linux"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Installation
      run: |
        python --version
        pip list

    - name: Run Jupyter Notebooks
      run: |
        for notebook in $(find ./src -name "*.ipynb"); do
          echo "Running $notebook"
          jupyter nbconvert --to notebook --execute "$notebook" --output "$(basename "${notebook%.ipynb}_linux_executed.ipynb")"
          echo ""
        done

    - name: Upload Executed Notebooks as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebooks-linux
        path: ./src/**/*_linux_executed.ipynb